# -*- coding: utf-8 -*-
# Deployment settings for Stage1.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Applications/Marmalade.app/Contents/s3e/makefile_builder/mkb.py', '--buildenv=xcode', '/Users/seanbollin/mkb/Stage1.mkb', '--deploy-only']
mkb = '/Users/seanbollin/mkb/Stage1.mkb'
mkf = ['/Applications/Marmalade.app/Contents/modules/iw2d/iw2d.mkf', '/Applications/Marmalade.app/Contents/modules/iwgx/iwgx.mkf', '/Applications/Marmalade.app/Contents/modules/iwgeom/iwgeom.mkf', '/Applications/Marmalade.app/Contents/modules/iwutil/iwutil.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libjpeg/libjpeg.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libpng/libpng.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/zlib/zlib.mkf', '/Applications/Marmalade.app/Contents/modules/iwresmanager/iwresmanager.mkf', '/Applications/Marmalade.app/Contents/modules/iwgl/iwgl.mkf', '/Applications/Marmalade.app/Contents/modules/iwgxfont/iwgxfont.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/tiniconv/tiniconv.mkf', '/Applications/Marmalade.app/Contents/modules/iw2dscenegraph/iw2dscenegraph.mkf', '/Applications/Marmalade.app/Contents/modules/iw2dscenegraphcore/iw2dscenegraphcore.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/seanbollin/mkb/data/fragment-shader.txt', 'fragment-shader.txt', 0),
    ('/Users/seanbollin/mkb/data/vertex-shader.txt', 'vertex-shader.txt', 0),
    ('/Users/seanbollin/mkb/data/textures', 'textures', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Stage1'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Stage1'
    long_caption = 'Stage1'
    version = [0, 0, 1]
    config = ['/Users/seanbollin/mkb/data/app.icf']
    data_dir = '/Users/seanbollin/mkb/data'
    iphone_link_lib = []
    wp8_ext_managed_dll = []
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = []
    iphone_link_libdirs = []
    iphone_link_opts = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    wp8_ext_native_dll = []
    win32_ext_dll = []
    android_so = []
    osx_ext_dll = []
    tizen_so = []
    wp8_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'x86' : {
                   'debug'   : r'/Users/seanbollin/mkb/build_stage1_xcode/build/Debug/Stage1.s86',
                   'release' : r'/Users/seanbollin/mkb/build_stage1_xcode/build/Release/Stage1.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'/Users/seanbollin/mkb/build_stage1_xcode/build/Debug ARM/Stage1.s3e',
                   'release' : r'/Users/seanbollin/mkb/build_stage1_xcode/build/Release ARM/Stage1.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
